export const ProductData = [
  {
    id: 1,
    name: "Product A",
    likes: 120,
    shares: 450,
    comments: 600,
    followers: 20000,
    category: "Tech",
    location: "USA",
  },
  {
    id: 2,
    name: "Product B",
    likes: 300,
    shares: 900,
    comments: 1200,
    followers: 50000,
    category: "Lifestyle",
    location: "Canada",
  },
  {
    id: 3,
    name: "Product C",
    likes: 1500,
    shares: 300,
    comments: 800,
    followers: 25000,
    category: "Food",
    location: "UK",
  },
  {
    id: 4,
    name: "Product D",
    likes: 2200,
    shares: 505,
    comments: 1000,
    followers: 3000,
    category: "Tech",
    location: "India",
  },
  {
    id: 5,
    name: "Product E",
    likes: 500,
    shares: 2000,
    comments: 3000,
    followers: 100000,
    category: "Fashion",
    location: "France",
  },
  {
    id: 6,
    name: "Product F",
    likes: 800,
    shares: 1500,
    comments: 2500,
    followers: 15000,
    category: "Travel",
    location: "Australia",
  },
  {
    id: 7,
    name: "Product G",
    likes: 4000,
    shares: 120,
    comments: 150,
    followers: 75000,
    category: "Tech",
    location: "Germany",
  },
  {
    id: 8,
    name: "Product H",
    likes: 90,
    shares: 250,
    comments: 4000,
    followers: 20000,
    category: "Health",
    location: "USA",
  },
  {
    id: 9,
    name: "Product I",
    likes: 1800,
    shares: 600,
    comments: 1100,
    followers: 40000,
    category: "Education",
    location: "Japan",
  },
  {
    id: 10,
    name: "Product J",
    likes: 2500,
    shares: 750,
    comments: 130,
    followers: 60000,
    category: "Tech",
    location: "South Korea",
  },
];
